services:
  # docker run --name mongoDB -d mongo:latest
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/api-esport
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    labels:
      - "traefik.http.routers.mongo-express.rule=Host(`mongo-express.localhost`)"

  api:
    build: .
    #ports:
    #  - 3001:3001
    depends_on:
      - mongo
    environment:
      PORT: 3001
      JWT_SECRET: EsportAPISecretKeyDecember2025
      DB_CONNECTION: mongodb://mongo:27017/api-sport
    volumes: 
      - uploads:/app/uploads
    labels:
      - "traefik.http.routers.api.rule=Host(`api-esport.localhost`)"

volumes:
  mongodata:
  uploads:

networks:
  default:
    external: true
    name: webproxy